import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { Card, CardHeader, Grid, Typography } from '@mui/material'
import {Layout} from '../components/layouts/Layout'
import { EntryList } from '../components/ui/EntryList'
import { NewEntry } from '../components/ui/NewEntry'

const inter = Inter({ subsets: ['latin'] })

export default function HomePage() {

console.log("cleinte key",process.env.NEXT_PUBLIC_CLIENT_KEY)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Grid container spacing={ 2 }>
            <Grid item xs={ 12 } sm={ 4 }>
              <Card sx={{ height: 'calc(100vh - 100px )' }}>
                <CardHeader title="Pendientes" />

                {/* Agregar una nueva entrada */}
                {/* Listado de las entradas */}
                <NewEntry />
                <EntryList status='pending'/>


              </Card>
            </Grid>

            <Grid item xs={ 12 } sm={ 4 }>
              <Card sx={{ height: 'calc(100vh - 100px )' }}>
                <CardHeader title="En Progreso" />
                <EntryList status='in-progress' />
              </Card>
            </Grid>

            <Grid item xs={ 12 } sm={ 4 }>
              <Card sx={{ height: 'calc(100vh - 100px )' }}>
                <CardHeader title="Completadas" />
                <EntryList status='finished' />
              </Card>
            </Grid>


        </Grid>
      </Layout>
    </>
  )
}
